### ISSUE TITLE
Top navigation links disappear on smaller screens size

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#696] opened 2022-08-05 10:37 UTC
#### Describe the bug
When browser window width is less than less than 1024 px, links in top bar disappear.

#### To Reproduce
Adjust  browser window width to less than 1024 px.

#### Expected behavior
Top bar links are visible and adjust responsively to width of browser window.

**Comment by ainoc** [comment] 2022-08-24 09:19
Duplicate.

**Comment by csc-felipe** [comment] 2023-03-31 10:52
> Duplicate.

It's a good practice to link to the duplicate. I can't find what is this a duplicate of, closing.

**Closed by csc-felipe** 2023-03-31 10:52 UTC
Labels: bug
